# .github/workflows/ansible-lint.yml
name: ansible-lint
 
on:
#  workflow_dispatch:
  push:
 
jobs:
  build:
    name: Ansible Lint # Naming the build is important to use it as a status check
    runs-on: ubuntu-latest
    env:
      docker_image: quay.io/brian_schonecker/mock/mock:latest
      # docker_image: fedora:latest
    steps:

      - uses: actions/checkout@v4

      - uses: bschonec/mock-srpm@prebuilt_docker_image
        with:
          chroot: centos-7-x86_64
          srpm: /tmp/*src.rpm
          #spec: test/simple/ant.spec
          image: quay.io/brian_schonecker/mock/mock:latest

#      - uses: jw3/mock-rpm@v0
#        with:
#          chroot: centos-7-x86_64
#          srpm: apache-*.src.rpm

#      - id: install-podman
#        run: sudo apt install -y podman
#        shell: bash
#
#      - id: create-container
#        run: "podman run -dt --privileged $docker_image > action.cid"
#        shell: bash
#
#      - id: copy_rpm
#        run: |
#          cid=$(cat action.cid)
#          podman exec $cid dnf -yq install mock
#          #podman exec $cid rpm -ivvh /tmp/apache-ant-1.9.7-1.el7.src.rpm
#          #podman exec $cid rm -f /root/rpmbuild/SOURCES/apache-ant-1.9.7-bin.tar.gz 
#          podman exec $cid mock -r centos-7-x86_64 --shell rpmbuild -ba --undefine=_disable_source_fetch /root/rpmbuild/SPECS/ant.spec
#        shell: bash
