# .github/workflows/ansible-lint.yml
name: ansible-lint
 
on:
#  workflow_dispatch:
  push:
 
jobs:
  build:
    name: Ansible Lint # Naming the build is important to use it as a status check
    runs-on: ubuntu-latest
    steps:
      - id: install-podman
        run: sudo apt install -y podman
        shell: bash
      - id: create-container
        run: podman run -dt --privileged fedora:latest > action.cid
        shell: bash
      - id: install_ping_dig
        run: |
          cid=$(cat action.cid)
          podman exec $cid dnf install -y /usr/bin/ping /usr/bin/dig /usr/bin/wget /usr/bin/rpmbuild
        shell: bash
      - id: copy_rpm
        run: |
          podman cp apache-ant-1.9.7-1.el7.src.rpm $cid:/tmp/
          podman exec $cid rpm -ivh /tmp/apache-ant-1.9.7-1.el7.src.rpm
          podman exec $cid '(cd ~/rpmbuild/SPECS/; rpmbuild -ba apache-ant-1.9.7-1.el7.src.rpm)'
        shell: bash
