# .github/workflows/ansible-lint.yml
name: Build Apache Ant SRPM
run-name: ${{ github.actor }} is testing out Github Actions.
 
on: [push]
 
jobs:
  example_matrix:
    strategy:
      matrix:
        chroot: [centos-7-x86_64, centos-8-x86_64, centos-9-x86_64]
    runs-on: ubuntu-latest
    env:
      docker_image: quay.io/brian_schonecker/mock/mock:latest
    steps:

      - uses: actions/checkout@v4

      - uses: bschonec/mock-srpm@prebuilt_docker_image
        with:
          chroot: "${{ matrix.chroot }}"
          spec: test/simple/ant.spec
          image: quay.io/brian_schonecker/mock/mock:latest
        if: false

      - run: |
          touch /tmp/${{ matrix.chroot }}   
          cat /etc/issue

      - run: echo "This job was triggered by ${{ github.event_name }} event."
      - run: echo "This job's status is ${{ job.status }}."
