# .github/workflows/ansible-lint.yml
name: ansible-lint
 
on:
#  workflow_dispatch:
  push:
 
jobs:
  build:
    name: Ansible Lint # Naming the build is important to use it as a status check
    runs-on: ubuntu-latest
    steps:
      - id: install-podman
        run: sudo apt install -y podman
        shell: bash
      - id: create-container
        run: podman run -dt --privileged fedora:latest > action.cid
        shell: bash
      - id: install_ping_dig
        run: |
          cid=$(cat action.cid)
          podman exec $cid dnf install -y /usr/bin/ping /usr/bin/dig /usr/bin/wget
        shell: bash
      - id: dig_xtek
        run: |
          cid=$(cat action.cid)
          podman exec $cid dig www.xtek.com
        shell: bash
      - id: ping_xtek
        run: |
          cid=$(cat action.cid)
          podman exec $cid wget http://www.xtek.com
        shell: bash
      - id: ping_IP_address
        run: |
          cid=$(cat action.cid)
          podman exec $cid ping -c 5 35.231.19.100
        shell: bash
