# .github/workflows/ansible-lint.yml
name: ansible-lint
 
on:
#  workflow_dispatch:
  push:
 
jobs:
  example_matrix:
    strategy:
      matrix:
        chroot: [centos-7-x86_64, centos-8-x86_64, centos-9-x86_64]
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - id: install-podman ${{ matrix.chroot }}
        run: echo ${{ matrix.chroot }}
        shell: bash

