# .github/workflows/ansible-lint.yml
name: ansible-lint
 
on:
#  workflow_dispatch:
  push:
 
jobs:
  build:
    name: Ansible Lint # Naming the build is important to use it as a status check
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4
      - id: install-podman
        run: sudo apt install -y podman
        shell: bash
      - id: create-container
        run: podman run -dt --privileged quay.io/brian_schonecker/mock/mock:rpmbuild > action.cid
        shell: bash
#      - id: install_ping_dig
#        run: |
#          cid=$(cat action.cid)
#          podman exec $cid dnf install -y /usr/bin/ping /usr/bin/dig /usr/bin/wget /usr/bin/rpmbuild
#        shell: bash
      - id: copy_rpm
        run: |
          cid=$(cat action.cid)
          podman cp apache-ant-1.9.7-1.el7.src.rpm $cid:/tmp/
          podman exec $cid ls -l /tmp
          podman exec $cid cd; ls -lR
          podman exec $cid rpm -ivh /tmp/apache-ant-1.9.7-1.el7.src.rpm
          podman exec $cid find / -type f -name ant.spc
          podman exec $cid cd ~/rpmbuild/SPECS/; rpmbuild -ba --undefine=_disable_source_fetch ant.spec
        shell: bash
